apiVersion: v1
kind: Service
metadata:
  name: mimir-nodeport
  namespace: observe
spec:
  selector:
    app: mimir
  ports:
    - name: nodeport
      port: 9009
      targetPort: 9009
      nodePort: 30009
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-headless
  namespace: observe
spec:
  clusterIP: None  # Headless Service로 설정
  selector:
    app: mimir
  ports:
    - port: 7946
      targetPort: 7946

