apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: observe
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  type: NodePort
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
      nodePort: 30910
