apiVersion: v1
kind: Service
metadata:
  name: tempo-distributor
  namespace: observe
spec:
  selector:
    app: tempo-distributor
  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: otlp
      protocol: TCP
      port: 4318
      targetPort: 4318

---
apiVersion: v1
kind: Service
metadata:
  name: tempo-ingester
  namespace: observe
spec:
  selector:
    app: tempo-ingester
  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: 3200

---
apiVersion: v1
kind: Service
metadata:
  name: tempo-querier
  namespace: observe
spec:
  selector:
    app: tempo-querier
  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095

---
apiVersion: v1
kind: Service
metadata:
  name: tempo-query-frontend
  namespace: observe
spec:
  selector:
    app: tempo-query-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095

