apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: observe
  labels:
    app: fluentd-config
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/syslog
      pos_file /var/log/syslog.pos
      @id input_syslog
      tag syslog
      <parse>
        @type none
      </parse>
    </source>

    <match syslog*>
      @type s3
      s3_endpoint "http://minio-headless:9000"
      s3_bucket logs
      aws_key_id minioadmin
      aws_sec_key minioadmin
      s3_region null
      s3_object_key_format "/#{ENV['NODE_IP']}/%Y-%m-%d/%{uuid_flush}%{tag}.gz"
      time_slice_format %y%m%d%H
      time_slice_wait 1m
      scheme http
      <buffer>
        @type memory
        flush_mode interval
        flush_interval 1s
        flush_thread_count 2
        retry_max_interval 30
        overflow_action block
      </buffer>
    </match>
