apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observe
  labels:
    app: loki-config
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100

    ingester:
      chunk_idle_period: 5m #
      chunk_retain_period: 30s

    common:
      ring:
        kvstore:
          store: memberlist
      replication_factor: 2
      compactor_address: loki-compactor-0.loki-headless-compactor:3100

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
        - loki-clusterip-distributor:7946 
        - loki-ingester-0.loki-headless-ingester:7946
        - loki-ingester-1.loki-headless-ingester:7946
        - loki-compactor-0.loki-headless-compactor:7946
        - loki-querier-0.loki-headless-querier:7946

    compactor:
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      shared_store: aws
      working_directory: /var/loki/compactor

    schema_config:
      configs:
      - from: 2024-04-15
        store: tsdb
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

    storage_config:
      aws:
        bucketnames: loki
        endpoint: http://minio-headless:9000
        s3: s3://minioadmin@http://minio-headless:9000/api/v1/service-account-credentials.:9000/loki
        region: null
        access_key_id: # s3 OR Minio key
        secret_access_key: # s3 OR Minio key
        s3forcepathstyle: true
      tsdb_shipper:
        active_index_directory: /data/tsdb-index
        cache_location: /data/tsdb-cache

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 10  # 초당 최대 10MB로 설정
      ingestion_burst_size_mb: 20  # 최대 버스트 사이즈를 20MB로 설정

    chunk_store_config:
      max_look_back_period: 365d

