apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: observe
  labels:
    app: mimir-config
data:
  mimir.yaml: |
    multitenancy_enabled: false
    target: distributor,ingester,querier,query-frontend,store-gateway,compactor

    activity_tracker: {}

    alertmanager: {}

    alertmanager_storage:
      backend: local

    server:
      http_listen_port: 9009
      log_level: warn
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000


    common:
      storage:
        backend: s3
        s3:
          endpoint: minio-headless:9000
          region: null
          secret_access_key: minioadmin
          access_key_id: minioadmin
          insecure: true

    blocks_storage:
      backend: s3
      s3:
        endpoint: minio-headless:9000
        bucket_name: mimir
        region: null
        secret_access_key: minioadmin
        access_key_id: minioadmin
        insecure: true

      tsdb:
        retention_period: 168h
        dir: /data/ingester


    ruler_storage:
      backend: filesystem
      local:
        directory: /tmp/mimir/rules

    distributor:
      pool:
        health_check_ingesters: true

    ingester:
      instance_limits:
        max_series: 1200000
      ring:
        final_sleep: 0s
        kvstore:
          store: memberlist
        min_ready_duration: 0s
        num_tokens: 512
        replication_factor: 1

    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
        - mimir-0.mimir.observe.svc.cluster.local:7946
        - mimir-1.mimir.observe.svc.cluster.local:7946

    compactor:
      sharding_ring:
        kvstore:
          store: memberlist

    limits:
      ingestion_burst_size: 500000
      ingestion_rate: 250000

