apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: observe
data:
  tempo.yaml: |
    stream_over_http_enabled: true
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318

    ingester:
      max_block_duration: 5m

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
        - tempo-distributor:7946
        - tempo-ingester-0:7946
        - tempo-ingester-1:7946
        - tempo-ingester-2:7946

    compactor:
      compaction:
        block_retention: 1h

    querier:
      frontend_worker:
        frontend_address: tempo-query-frontend:9095

    query_frontend:
      max_batch_size: 100

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: docker-compose
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://prometheus-nodeport/api/v1/write
            send_exemplars: true

    storage:
      trace:
        blocklist_poll: 2s
        backend: s3
        s3:
          bucket: tempo
          endpoint: minio-headless:9000
          access_key: # s3 OR Minio key
          secret_key: # s3 OR Minio key
          region: null
          insecure: true
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks

    overrides:
      defaults:
        metrics_generator:
          processors: ['service-graphs', 'span-metrics']

