apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data2-1-pvc
  namespace: observe
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data2-2-pvc
  namespace: observe
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 10Gi

