apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-querier
  namespace: observe
spec:
  serviceName: "loki-headless-querier"
  replicas: 1
  selector:
    matchLabels:
      app: loki-querier
  template:
    metadata:
      labels:
        app: loki-querier
    spec:
      containers:
      - name: loki-querier
        image: grafana/loki:2.8.0
        command: ["/usr/bin/loki"]
        args:
          - "-config.file=/etc/loki/loki.yaml"
          - "-target=querier"
          - "-config.expand-env=true"
        ports:
        - containerPort: 3100
        - containerPort: 7946
        volumeMounts:
        - name: config-volume
          mountPath: /etc/loki/loki.yaml
          subPath: loki.yaml
        securityContext:
          runAsUser: 0
      volumes:
      - name: config-volume
        configMap:
          name: loki-config
          items:
            - key: loki.yaml
              path: loki.yaml
