 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: app-deployment
   namespace: app
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: app
   template:
     metadata:
       labels:
         app: app
     spec:
       containers:
         - name: app
           image: app:latest
           imagePullPolicy: Never
           securityContext:
             runAsUser: 0
           env:
             - name: APP_NAME
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
           ports:
             - containerPort: 5000

