apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-ui
  namespace: deepseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-ui
  template:
    metadata:
      labels:
        app: deepseek-ui
    spec:
      containers:
      - name: deepseek-ui
        image: ghcr.io/ollama-webui/ollama-webui:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/data
          name: deepseek-ui-storage
        env:
        - name: OLLAMA_API_BASE_URL
          value: "http://deepseek-server:11434/api"
      volumes:
      - name: deepseek-ui-storage
        persistentVolumeClaim:
          claimName: deepseek-ui-pvc
