apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-querier
  namespace: observe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo-querier
  template:
    metadata:
      labels:
        app: tempo-querier
    spec:
      containers:
        - name: tempo-querier
          image: grafana/tempo:2.4.1
          args:
            - "-target=querier"
            - "-config.file=/etc/tempo.yaml"
          ports:
            - containerPort: 3200
          volumeMounts:
            - name: config-volume
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: config-volume
          configMap:
            name: tempo-config
