apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: #base64 encoding 필요
  AWS_SECRET_ACCESS_KEY:  #base64 encoding 필요
  AWS_ENDPOINTS:  #base64 encoding 필요
