apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-ingester
  namespace: observe
spec:
  serviceName: "loki-headless-ingester"
  replicas: 2
  selector:
    matchLabels:
      app: loki-ingester
  template:
    metadata:
      labels:
        app: loki-ingester
    spec:
      containers:
      - name: loki-ingester
        image: grafana/loki:2.8.0
        command: ["/usr/bin/loki"]
        args:
          - "-config.file=/etc/loki/loki.yaml"
          - "-target=ingester"
          - "-config.expand-env=true"
        ports:
        - containerPort: 3100
        - containerPort: 7946
        volumeMounts:
        - name: config-volume
          mountPath: /etc/loki/loki.yaml
          subPath: loki.yaml
        securityContext:
          runAsUser: 0
      volumes:
      - name: config-volume
        configMap:
          name: loki-config
          items:
            - key: loki.yaml
              path: loki.yaml
