apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: blackbox
  namespace: observe
spec:
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter:v0.25.0
          command:
            - --config.file=/etc/blackbox/blackbox.yml
            - --web.config.file=/etc/config/web.yml
          volumeMounts:
            - mountPath: /etc/blackbox/blackbox.yml
              name: blackbox-conf
              readOnly: true
          ports:
            - containerPort: 9115
      volumes:
        - name: blackbox-conf
          hostPath:
            path: /home/config/blackbox/blackbox.yml
