apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: observe
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: jooseyoon/sebong:fluentd-s3-latest
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - mountPath: /var/log
              name: var-log
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /fluentd/etc/fluentd.conf
              name: fluentd-config-volume
              subPath: fluentd.conf
          command:
            - /bin/sh
            - -c
            - |
              exec fluentd -c /fluentd/etc/fluentd.conf
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: fluentd-config-volume
          configMap:
            name: fluentd-config

