apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: observe
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/etc/promtail/config.yaml
            - -config.expand-env=true
          volumeMounts:
            - mountPath: /var/log
              name: var-log
            - mountPath: /var/log/journal
              name: var-log-journal
            - mountPath: /etc/machine-id
              name: machine-id
            - mountPath: /etc/promtail/config.yaml
              name: promtail-config-volume
              subPath: config.yaml
            - mountPath: /etc/localtime
              name: local-time
              readOnly: true
          ports:
            - containerPort: 1514
              protocol: UDP
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
        - name: var-log-journal
          hostPath:
            path: /var/log/journal
        - name: machine-id
          hostPath:
            path: /etc/machine-id
        - name: local-time
          hostPath:
            path: /etc/localtime
        - name: promtail-config-volume
          configMap:
            name: promtail-config
            
