defaults:
  revision: "1-23-4"

  # istiod 리소스 설정
  pilot:
    autoscaleMin: 1
    autoscaleMax: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi

  # istio-proxy sidecar 리소스 설정
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 128Mi
