apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ingress-app  # 필요에 따라 실제 도메인으로 변경
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: observe
spec:
  selector:
    app: app
  ports:
    - name: nodeport
      port: 5000
      targetPort: 5000
      nodePort: 30100    # NodePort 서비스 설정
  type: NodePort

