apiVersion: v1
kind: Service
metadata:
  name: deepseek-ui
  namespace: deepseek
spec:
  type: NodePort
  selector:
    app: deepseek-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30888
---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-server
  namespace: deepseek
spec:
  selector:
    app: deepseek-server
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434

