apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport-distributor
  namespace: observe
spec:
  selector:
    app: loki-distributor
  ports:
    - name: nodeport
      port: 3100
      targetPort: 3100
      nodePort: 30031
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless-ingester
  namespace: observe
spec:
  clusterIP: None
  selector:
    app: loki-ingester
  ports:
    - port: 7946
      targetPort: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless-querier
  namespace: observe
spec:
  clusterIP: None
  selector:
    app: loki-querier
  ports:
    - port: 3100
      targetPort: 3100
      name: http
    - port: 7946
      targetPort: 7946
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: loki-clusterip-distributor
  namespace: observe
spec:
  selector:
    app: loki-distributor
  ports:
    - port: 7946
      targetPort: 7946
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless-compactor
  namespace: observe
spec:
  clusterIP: None  # Headless Service로 설정
  selector:
    app: loki-compactor
  ports:
    - port: 7946
      targetPort: 7946
      name: grpc
    - port: 3100
      targetPort: 3100
      name: http
