apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport-ui
  namespace: observe
spec:
  selector:
    app: minio
  ports:
    - name: nodeport
      port: 9001
      targetPort: 9001
      nodePort: 30091    # NodePort 서비스 설정
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport-api
  namespace: observe
spec:
  selector:
    app: minio
  ports:
    - name: nodeport
      port: 9000
      targetPort: 9000
      nodePort: 30090
  type: NodePort

