apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: observe
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000

